pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: true, description: "Should Enable service: ", name:"myBoolean")
    }
    stages {
        
        stage('Completed') {
            steps {
                echo "Parameters Build Job: ${params.myBoolean}"
            }
        }
    }
}
