pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: "Confrim Deployment: ", name:"confirmDeployment")
        string(defaultValue: "Test", description: "Deployment Name", name: "deployname")
        choice(choices:['EU-WEST-2A', 'EU-WEST-2B', 'EU-WEST-2C', 'local'], description: 'select a region', name: "choices")
    }
    environment {
        Hello = "World"
    }
    stages {
        stage('Completed') {
            steps {
                echo "Deployment Name: ${params.deployname}"
                echo "Confirm deployment: ${params.confirmDeployment}"
                echo "Deployment done in region: ${params.choices}"
                echo "Printing Hello $Hello"
            }   
        }
    }
}
